In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df= pd.DataFrame({'X':[1,2,3,4,5],
              'Y': [6,4,5,5,10]})

In [3]:
df

X   Y
0  1   6
1  2   4
2  3   5
3  4   5
4  5  10

In [4]:
from sklearn.linear_model import LinearRegression

In [5]:
model=LinearRegression()
model.fit(df[['X']],df['Y'])

LinearRegression()

In [6]:
model.intercept_

3.3000000000000003

In [7]:
model.coef_

array([0.9])

In [8]:
ypred=model.predict(df[['X']])
ypred

array([4.2, 5.1, 6. , 6.9, 7.8])

In [9]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(df['Y'],ypred)
mse

2.779999999999999

In [10]:
import numpy as np
np.sqrt(mse)

1.6673332000533063

In [11]:
model.score(df[['X']],df[['Y']])

0.3681818181818184

In [12]:
dff= pd.DataFrame({'X':[1,2,3,4,5],
              'Y': [6,7,8,9,10]})

In [13]:
model.predict([[6]])

/Users/ayeshanausheen/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8.7])

In [14]:
dff= pd.DataFrame({'A':[1,2,3,4,5],
              'B': [6,7,8,9,10]})

In [15]:
dff

A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
model1 =LinearRegression()
model.fit(dff[['A']],dff['B'])

LinearRegression()

In [18]:
model.intercept_

5.0

In [19]:
 model.predict(dff[['A']])

array([ 6.,  7.,  8.,  9., 10.])

In [20]:
model.coef_

array([1.])

In [21]:
ypred=model.predict(dff[['A']])
ypred

array([ 6.,  7.,  8.,  9., 10.])

In [22]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(dff['B'],ypred)
mse

0.0

In [23]:
import numpy as np
np.sqrt(mse)

0.0

In [24]:
model.score(dff[['A']],dff[['B']])

1.0

In [25]:
model.predict([[6]])

/Users/ayeshanausheen/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.])

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [27]:
a= pd.DataFrame({'X':[1,2,3,4,5],
              'Y': [6,7,8,9,10]})

In [28]:
a

X   Y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [29]:
X=a[['X']]
y=a[['Y']]

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [31]:
X_train

X
3  4
2  3
4  5
0  1

In [32]:
X_test

X
1  2

In [33]:
y_train

Y
3   9
2   8
4  10
0   6

In [34]:
y_test

Y
1  7

In [35]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [36]:
model.coef_

array([[1.]])

In [37]:
model.intercept_

array([5.])

In [38]:
ypred_train=model.predict(X_train)
ypred_train

array([[ 9.],
       [ 8.],
       [10.],
       [ 6.]])

In [39]:
ypred_test=model.predict(X_test)
ypred_test

array([[7.]])

In [40]:
model.score(X_train,y_train)

1.0

In [41]:
model.score(X_test,y_test)

/Users/ayeshanausheen/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


nan

# Common steps for ML algorithms
1. Modelling
    - Step 1: Import ML algorithms
    - Step 2: model=ML algorithm
    - Step 3: fit the model with X_train, y_train
2. Prediction
    - Step 4: predict on X_train
    - Step 5: predict on X_test
3. Evaluation
    - Step 6: Do calculations according to the ML algorithm selected
4. Selection
    - Step 7: Select the best ML model by checking 
        * train accuracy = test accuracy(+or-5% difference)
    - Step 8: Check cross validation score=test accuracy
    - Step 9: Check the client requrements
    - Step 10: Submit